apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trading-service
  template:
    metadata:
      labels:
        app: trading-service
    spec:
      containers:
      - name: trading-service
        image: your-dockerhub-username/trading-service:latest
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: trading-service
spec:
  selector:
    app: trading-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
